# Generated by Django 4.0.1 on 2022-09-16 08:09

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='date',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='description',
            new_name='post_name',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='content',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='description',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='meta_keywords',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='meta_title',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='post_title',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='tags',
        ),
        migrations.AddField(
            model_name='blog',
            name='blog_content',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='blog',
            name='blog_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='blog',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='blog',
            name='tag_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='blog',
            name='update_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 9, 16, 8, 8, 27, 758076, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='post',
            name='post_content',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='post',
            name='post_header',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='post',
            name='tag_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='update_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 9, 16, 8, 9, 4, 917307, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
