# Generated by Django 4.0.1 on 2022-09-16 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_blog_is_approved'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
